canonical: "https://afriscic.github.io/EAHP_Interoperabillty/"
fhirVersion: 5.0.0
FSHOnly: true
applyExtensionMetadataToRoot: false
id: eahp-interoperability-ig
name: EAHPInteroperabilityIG
status: draft
version: "0.0.1"
package-id: "org.eahp.interoperability"
dependencies: {}
